# Generated by Django 4.1.7 on 2023-08-21 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("obreplace_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="watchlist",
            name="platform",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="watch_platform",
                to="obreplace_app.streamplatform",
            ),
            preserve_default=False,
        ),
    ]
